#!/bin/zsh
#
# plugins/development/xcode.sh - Xcode data cleanup plugin
#

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# Check if Xcode is running
_check_xcode_running() {
  if pgrep -x "Xcode" >/dev/null 2>&1 || pgrep -f "com.apple.dt.Xcode" >/dev/null 2>&1; then
    return 0  # Xcode is running
  fi
  return 1  # Xcode is not running
}

# Helper function to clean a directory safely (used for safe temp files)
_clean_xcode_dir_safe() {
  local dir="$1"
  local description="$2"
  local backup_name="$3"
  
  if [[ ! -d "$dir" ]]; then
    echo "0"
    return 0
  fi
  
  local space_before=$(calculate_size_bytes "$dir")
  
  if [[ $space_before -eq 0 ]]; then
    echo "0"
    return 0
  fi
  
  # safe_clean_dir handles backup internally, so we don't need to call backup here
  # This avoids double backup and potential conflicts
  safe_clean_dir "$dir" "$description" || {
    print_error "Failed to clean $description" >&2
    log_message "ERROR" "safe_clean_dir failed for $description: $dir"
    echo "0"
    return 1
  }
  
  # Wait a moment for filesystem to update (especially if Xcode is running)
  sleep 0.5 2>/dev/null || true
  
  # Verify the directory was actually cleaned
  local space_after=$(calculate_size_bytes "$dir")
  local space_freed=$((space_before - space_after))
  
  # Validate space_freed is not negative
  if [[ $space_freed -lt 0 ]]; then
    space_freed=0
    log_message "WARNING" "Directory size increased during cleanup: $dir (before: $(format_bytes $space_before), after: $(format_bytes $space_after))"
  fi
  
  # Log if cleanup didn't free expected space (possible issue with deletion)
  if [[ $space_freed -eq 0 && $space_before -gt 0 ]]; then
    log_message "WARNING" "Cleanup reported success but no space was freed for $description: $dir (size before: $(format_bytes $space_before), size after: $(format_bytes $space_after))"
    # Check if directory still has files
    local item_count=$(find "$dir" -mindepth 1 -maxdepth 1 2>/dev/null | wc -l | tr -d ' ')
    if [[ $item_count -gt 0 ]]; then
      log_message "WARNING" "Directory still contains $item_count item(s) after cleanup: $dir"
      # Try more aggressive deletion for Xcode cache directories
      # These are safe to force-delete even if locked (they'll be regenerated)
      if _check_xcode_running; then
        log_message "INFO" "Xcode is running - attempting force deletion of locked files in $dir"
        # Try to delete files even if they appear locked
        # Use find with -delete which is more aggressive
        find "$dir" -mindepth 1 -type f -delete 2>/dev/null || true
        find "$dir" -mindepth 1 -type d -empty -delete 2>/dev/null || true
        # Recalculate after force deletion
        sleep 0.5 2>/dev/null || true
        space_after=$(calculate_size_bytes "$dir")
        space_freed=$((space_before - space_after))
        if [[ $space_freed -gt 0 ]]; then
          log_message "INFO" "Force deletion freed $(format_bytes $space_freed) for $description"
        fi
      fi
    fi
  fi
  
  # Only print warning if space wasn't freed (useful diagnostic)
  local quiet_mode="${MC_QUIET_MODE:-false}"
  if [[ $space_freed -eq 0 && $space_before -gt 0 && "$quiet_mode" != "true" ]]; then
    print_warning "No space was freed for $description. Files may be locked by Xcode." >&2
    print_info "Try closing Xcode and running cleanup again." >&2
  fi
  
  echo "$space_freed"
  return 0
}

# Helper function to find and clean old files/directories (older than N days)
_clean_xcode_old_items() {
  local base_dir="$1"
  local description="$2"
  local backup_name="$3"
  local days_old="${4:-90}"
  
  if [[ ! -d "$base_dir" ]]; then
    echo "0"
    return 0
  fi
  
  # Find directories older than specified days
  local old_items=()
  local total_size_before=0
  while IFS= read -r item; do
    if [[ -n "$item" && -e "$item" ]]; then
      old_items+=("$item")
    fi
  done < <(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -mtime +$days_old 2>/dev/null)
  
  if [[ ${#old_items[@]} -eq 0 ]]; then
    echo "0"
    return 0
  fi
  
  local total_space_freed=0
  
  for item in "${old_items[@]}"; do
    local item_name=$(basename "$item")
    local space_before=$(calculate_size_bytes "$item")
    
    if [[ $space_before -eq 0 ]]; then
      continue
    fi
    
    if ! backup "$item" "${backup_name}_${item_name}"; then
      print_warning "Backup failed for $item_name. Skipping." >&2
      log_message "WARNING" "Backup failed for $item, skipping"
      continue
    fi
    
    safe_remove "$item" "$description: $item_name" || {
      print_warning "Failed to remove $item_name" >&2
      continue
    }
    
    total_space_freed=$((total_space_freed + space_before))
  done
  
  echo "$total_space_freed"
  return 0
}

# Clean safe Xcode temp files (caches, simulator caches, documentation cache)
# These are always safe to delete and will be regenerated by Xcode
clean_xcode_safe_temp_files() {
  local quiet_mode="${MC_QUIET_MODE:-false}"
  
  # Warn if Xcode is running (files may be locked or regenerated immediately)
  if _check_xcode_running; then
    if [[ "$quiet_mode" != "true" ]]; then
      print_warning "Xcode is currently running. Some files may be locked and will be cleaned when Xcode is closed."
      print_info "For best results, close Xcode before running cleanup."
    fi
    log_message "WARNING" "Xcode is running during cleanup - some files may be locked"
  fi
  
  local total_space_freed=0
  local space_freed=0
  
  # Xcode Caches (always safe)
  space_freed=$(_clean_xcode_dir_safe \
    "$HOME/Library/Caches/com.apple.dt.Xcode" \
    "Xcode Caches" \
    "xcode_caches")
  total_space_freed=$((total_space_freed + space_freed))
  
  # CoreSimulator Caches (always safe)
  space_freed=$(_clean_xcode_dir_safe \
    "$HOME/Library/Developer/CoreSimulator/Caches" \
    "CoreSimulator Caches" \
    "xcode_simulator_caches")
  total_space_freed=$((total_space_freed + space_freed))
  
  # Documentation Cache (always safe)
  space_freed=$(_clean_xcode_dir_safe \
    "$HOME/Library/Developer/Xcode/DocumentationCache" \
    "Xcode Documentation Cache" \
    "xcode_documentation_cache")
  total_space_freed=$((total_space_freed + space_freed))
  
  if [[ $total_space_freed -eq 0 ]]; then
    track_space_saved "Xcode Safe Temp Files" 0 "true"
  else
    track_space_saved "Xcode Safe Temp Files" $total_space_freed "true"
  fi
  
  return 0
}

# Clean Xcode Derived Data (with option to keep recent)
clean_xcode_derived_data() {
  local quiet_mode="${MC_QUIET_MODE:-false}"
  
  local derived_data_dir="$HOME/Library/Developer/Xcode/DerivedData"
  if [[ ! -d "$derived_data_dir" ]]; then
    track_space_saved "Xcode Derived Data" 0
    return 0
  fi
  
  # Check if user wants to clean all or just old derived data
  local clean_all=false
  
  if [[ "$MC_DRY_RUN" == "true" ]]; then
    # In dry-run, default to cleaning all
    clean_all=true
  elif [[ -t 0 ]] && [[ -t 1 ]]; then
    print_info "Options:"
    print_info "  1) Clean all derived data (may require rebuilding all projects)"
    print_info "  2) Clean only old derived data (older than 90 days)"
    print_info "  3) Skip derived data cleanup"
    
    local choice=""
    local loop_count=0
    while [[ -z "$choice" ]]; do
      loop_count=$((loop_count + 1))
      # Use timeout to prevent hanging
      if ! read -t 30 -r "choice?Enter choice (1-3): "; then
        print_warning "Input timeout. Using default: clean only old derived data (older than 90 days)."
        clean_all=false
        break
      fi
      case "$choice" in
        1)
          clean_all=true
          ;;
        2)
          clean_all=false
          ;;
        3)
          print_info "Skipping Xcode Derived Data cleanup"
          track_space_saved "Xcode Derived Data" 0
          return 0
          ;;
        *)
          print_warning "Invalid choice. Please enter 1, 2, or 3."
          choice=""
          ;;
      esac
    done
  else
    # Non-interactive terminal - clean ALL derived data (safe default)
    # Derived data is safe to delete - Xcode will rebuild it as needed
    clean_all=true  # Clean all derived data - it's safe and will be regenerated
  fi
  
  local total_space_freed=0
  
  if [[ "$clean_all" == "true" ]]; then
    # Clean all derived data
    local space_freed=$(_clean_xcode_dir_safe \
      "$derived_data_dir" \
      "Xcode Derived Data" \
      "xcode_derived_data")
    total_space_freed=$((total_space_freed + space_freed))
  else
    # Clean only old derived data (older than 90 days)
    local space_freed=$(_clean_xcode_old_items \
      "$derived_data_dir" \
      "Xcode Derived Data" \
      "xcode_derived_data" \
      90)
    total_space_freed=$((total_space_freed + space_freed))
  fi
  
  if [[ $total_space_freed -eq 0 ]]; then
    track_space_saved "Xcode Derived Data" 0
  else
    track_space_saved "Xcode Derived Data" $total_space_freed "true"
  fi
  
  return 0
}

# Clean Xcode Device Support (with option to keep recent)
clean_xcode_device_support() {
  local quiet_mode="${MC_QUIET_MODE:-false}"
  
  local device_support_dir="$HOME/Library/Developer/Xcode/iOS DeviceSupport"
  if [[ ! -d "$device_support_dir" ]]; then
    track_space_saved "Xcode Device Support" 0
    return 0
  fi
  
  # Check if user wants to clean all or just old device support
  local clean_all=false
  
  if [[ "$MC_DRY_RUN" == "true" ]]; then
    # In dry-run, default to cleaning all
    clean_all=true
  elif [[ -t 0 ]] && [[ -t 1 ]]; then
    print_info "Options:"
    print_info "  1) Clean all device support (will re-download when devices connect)"
    print_info "  2) Clean only old device support (older than 90 days)"
    print_info "  3) Skip device support cleanup"
    
    local choice=""
    local loop_count=0
    while [[ -z "$choice" ]]; do
      loop_count=$((loop_count + 1))
      # Use timeout to prevent hanging
      if ! read -t 30 -r "choice?Enter choice (1-3): "; then
        print_warning "Input timeout. Using default: clean only old device support (older than 90 days)."
        clean_all=false
        break
      fi
      case "$choice" in
        1)
          clean_all=true
          ;;
        2)
          clean_all=false
          ;;
        3)
          print_info "Skipping Xcode Device Support cleanup"
          track_space_saved "Xcode Device Support" 0
          return 0
          ;;
        *)
          print_warning "Invalid choice. Please enter 1, 2, or 3."
          choice=""
          ;;
      esac
    done
  else
    # Non-interactive terminal - clean ALL device support (safe default)
    # Device support can be re-downloaded when devices connect
    clean_all=true  # Clean all device support - it can be re-downloaded
  fi
  
  local total_space_freed=0
  
  if [[ "$clean_all" == "true" ]]; then
    # Clean all device support
    local space_freed=$(_clean_xcode_dir_safe \
      "$device_support_dir" \
      "Xcode Device Support" \
      "xcode_device_support")
    total_space_freed=$((total_space_freed + space_freed))
  else
    # Clean only old device support (older than 90 days)
    local space_freed=$(_clean_xcode_old_items \
      "$device_support_dir" \
      "Xcode Device Support" \
      "xcode_device_support" \
      90)
    total_space_freed=$((total_space_freed + space_freed))
  fi
  
  if [[ $total_space_freed -eq 0 ]]; then
    track_space_saved "Xcode Device Support" 0
  else
    track_space_saved "Xcode Device Support" $total_space_freed "true"
  fi
  
  return 0
}

# Clean Xcode Archives (with optional age filter)
clean_xcode_archives() {
  local quiet_mode="${MC_QUIET_MODE:-false}"
  
  local archives_dir="$HOME/Library/Developer/Xcode/Archives"
  if [[ ! -d "$archives_dir" ]]; then
    track_space_saved "Xcode Archives" 0
    return 0
  fi
  
  # Always require confirmation for archives
  if [[ "$MC_DRY_RUN" != "true" ]] && ! mc_confirm "Do you want to clean Xcode Archives?"; then
    print_info "Skipping Xcode Archives cleanup"
    track_space_saved "Xcode Archives" 0
    return 0
  fi
  
  # Check if user wants to clean all or just old archives
  local clean_all=false
  
  if [[ "$MC_DRY_RUN" == "true" ]]; then
    # In dry-run, default to cleaning all
    clean_all=true
  elif [[ -t 0 ]] && [[ -t 1 ]]; then
    print_info "Options:"
    print_info "  1) Clean all archives"
    print_info "  2) Clean only old archives (older than 90 days)"
    print_info "  3) Cancel"
    
    local choice=""
    local loop_count=0
    while [[ -z "$choice" ]]; do
      loop_count=$((loop_count + 1))
      # Use timeout to prevent hanging
      if ! read -t 30 -r "choice?Enter choice (1-3): "; then
        print_warning "Input timeout. Cancelling archives cleanup."
        track_space_saved "Xcode Archives" 0
        return 0
      fi
      case "$choice" in
        1)
          clean_all=true
          ;;
        2)
          clean_all=false
          ;;
        3)
          print_info "Cancelling Xcode Archives cleanup"
          track_space_saved "Xcode Archives" 0
          return 0
          ;;
        *)
          print_warning "Invalid choice. Please enter 1, 2, or 3."
          choice=""
          ;;
      esac
    done
  else
    # Non-interactive terminal - skip archives cleanup (requires explicit confirmation)
    track_space_saved "Xcode Archives" 0
    return 0
  fi
  
  local total_space_freed=0
  
  if [[ "$clean_all" == "true" ]]; then
    # Clean all archives
    local space_freed=$(_clean_xcode_dir_safe \
      "$archives_dir" \
      "Xcode Archives" \
      "xcode_archives")
    total_space_freed=$((total_space_freed + space_freed))
  else
    # Clean only old archives (older than 90 days)
    print_info "Cleaning archives older than 90 days..."
    local space_freed=$(_clean_xcode_old_items \
      "$archives_dir" \
      "Xcode Archives" \
      "xcode_archives" \
      90)
    total_space_freed=$((total_space_freed + space_freed))
  fi
  
  if [[ $total_space_freed -eq 0 ]]; then
    track_space_saved "Xcode Archives" 0
  else
    track_space_saved "Xcode Archives" $total_space_freed "true"
  fi
  
  return 0
}

# Main cleanup function (backward compatibility)
# This function coordinates all Xcode cleanup operations
clean_xcode_data() {
  local total_space_freed=0
  local space_freed=0
  
  # 1. Clean safe temp files (no warnings, auto-clean - these are always safe)
  clean_xcode_safe_temp_files
  space_freed=$(get_space_saved "Xcode Safe Temp Files")
  total_space_freed=$((total_space_freed + space_freed))
  
  # 2. Clean derived data (with options - asks user for preferences)
  clean_xcode_derived_data
  space_freed=$(get_space_saved "Xcode Derived Data")
  total_space_freed=$((total_space_freed + space_freed))
  
  # 3. Clean device support (with options - asks user for preferences)
  clean_xcode_device_support
  space_freed=$(get_space_saved "Xcode Device Support")
  total_space_freed=$((total_space_freed + space_freed))
  
  # 4. Clean archives (requires confirmation - asks user explicitly)
  clean_xcode_archives
  space_freed=$(get_space_saved "Xcode Archives")
  total_space_freed=$((total_space_freed + space_freed))
  
  if [[ $total_space_freed -eq 0 ]]; then
    track_space_saved "Xcode Data" 0
  else
    track_space_saved "Xcode Data" $total_space_freed "true"
    # Always print success message if space was freed
    print_success "Xcode cleanup completed! Freed $(format_bytes $total_space_freed)."
  fi
  
  return 0
}

# Size calculation function for sweep
_calculate_xcode_data_size_bytes() {
  local size_bytes=0
  local xcode_size=0
  local xcode_dirs=(
    "$HOME/Library/Developer/Xcode/DerivedData"
    "$HOME/Library/Developer/Xcode/Archives"
    "$HOME/Library/Developer/Xcode/iOS DeviceSupport"
    "$HOME/Library/Caches/com.apple.dt.Xcode"
    "$HOME/Library/Developer/CoreSimulator/Caches"
    "$HOME/Library/Developer/Xcode/DocumentationCache"
  )
  for dir in "${xcode_dirs[@]}"; do
    if [[ -d "$dir" ]]; then
      local dir_size=$(calculate_size_bytes "$dir" 2>/dev/null || echo "0")
      [[ "$dir_size" =~ ^[0-9]+$ ]] && xcode_size=$((xcode_size + dir_size))
    fi
  done
  size_bytes=$xcode_size
  echo "$size_bytes"
}

# Register plugin with size function
register_plugin "Xcode Data" "development" "clean_xcode_data" "false" "_calculate_xcode_data_size_bytes"
