#!/bin/zsh
#
# plugins/development/xcode.sh - Xcode data cleanup plugin
#

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# Helper function to clean a directory safely (used for safe temp files)
_clean_xcode_dir_safe() {
  local dir="$1"
  local description="$2"
  local backup_name="$3"
  
  if [[ ! -d "$dir" ]]; then
    echo "0"
    return 0
  fi
  
  local space_before=$(calculate_size_bytes "$dir")
  if [[ $space_before -eq 0 ]]; then
    echo "0"
    return 0
  fi
  
  if ! backup "$dir" "$backup_name"; then
    print_error "Backup failed for $description. Skipping this directory." >&2
    log_message "ERROR" "Backup failed for $description, skipping"
    echo "0"
    return 1
  fi
  
  safe_clean_dir "$dir" "$description" || {
    print_error "Failed to clean $description" >&2
    echo "0"
    return 1
  }
  
  local space_after=$(calculate_size_bytes "$dir")
  local space_freed=$((space_before - space_after))
  
  # Validate space_freed is not negative
  if [[ $space_freed -lt 0 ]]; then
    space_freed=0
    log_message "WARNING" "Directory size increased during cleanup: $dir"
  fi
  
  if [[ $space_freed -gt 0 ]]; then
    print_success "Cleaned $description ($(format_bytes $space_freed))." >&2
  fi
  
  echo "$space_freed"
  return 0
}

# Helper function to find and clean old files/directories (older than N days)
_clean_xcode_old_items() {
  local base_dir="$1"
  local description="$2"
  local backup_name="$3"
  local days_old="${4:-90}"
  
  if [[ ! -d "$base_dir" ]]; then
    echo "0"
    return 0
  fi
  
  # Find directories older than specified days
  local old_items=()
  while IFS= read -r item; do
    if [[ -n "$item" && -e "$item" ]]; then
      old_items+=("$item")
    fi
  done < <(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -mtime +$days_old 2>/dev/null)
  
  if [[ ${#old_items[@]} -eq 0 ]]; then
    echo "0"
    return 0
  fi
  
  local total_space_freed=0
  
  for item in "${old_items[@]}"; do
    local item_name=$(basename "$item")
    local space_before=$(calculate_size_bytes "$item")
    
    if [[ $space_before -eq 0 ]]; then
      continue
    fi
    
    if ! backup "$item" "${backup_name}_${item_name}"; then
      print_warning "Backup failed for $item_name. Skipping." >&2
      log_message "WARNING" "Backup failed for $item, skipping"
      continue
    fi
    
    safe_remove "$item" "$description: $item_name" || {
      print_warning "Failed to remove $item_name" >&2
      continue
    }
    
    total_space_freed=$((total_space_freed + space_before))
    print_success "Removed old $item_name ($(format_bytes $space_before))." >&2
  done
  
  echo "$total_space_freed"
  return 0
}

# Clean safe Xcode temp files (caches, simulator caches, documentation cache)
# These are always safe to delete and will be regenerated by Xcode
clean_xcode_safe_temp_files() {
  print_header "Cleaning Xcode Safe Temp Files"
  print_info "Cleaning Xcode caches and temporary files (safe to delete, will be regenerated)..."
  
  local total_space_freed=0
  local space_freed=0
  
  # Xcode Caches (always safe)
  space_freed=$(_clean_xcode_dir_safe \
    "$HOME/Library/Caches/com.apple.dt.Xcode" \
    "Xcode Caches" \
    "xcode_caches")
  total_space_freed=$((total_space_freed + space_freed))
  
  # CoreSimulator Caches (always safe)
  space_freed=$(_clean_xcode_dir_safe \
    "$HOME/Library/Developer/CoreSimulator/Caches" \
    "CoreSimulator Caches" \
    "xcode_simulator_caches")
  total_space_freed=$((total_space_freed + space_freed))
  
  # Documentation Cache (always safe)
  space_freed=$(_clean_xcode_dir_safe \
    "$HOME/Library/Developer/Xcode/DocumentationCache" \
    "Xcode Documentation Cache" \
    "xcode_documentation_cache")
  total_space_freed=$((total_space_freed + space_freed))
  
  if [[ $total_space_freed -eq 0 ]]; then
    print_info "No Xcode temp files found to clean."
    track_space_saved "Xcode Safe Temp Files" 0 "true"
  else
    track_space_saved "Xcode Safe Temp Files" $total_space_freed "true"
  fi
  
  return 0
}

# Clean Xcode Derived Data (with option to keep recent)
clean_xcode_derived_data() {
  print_header "Cleaning Xcode Derived Data"
  print_info "Derived data contains build artifacts. Xcode will rebuild projects as needed."
  
  local derived_data_dir="$HOME/Library/Developer/Xcode/DerivedData"
  if [[ ! -d "$derived_data_dir" ]]; then
    print_info "No Xcode Derived Data found."
    track_space_saved "Xcode Derived Data" 0
    return 0
  fi
  
  # Check if user wants to clean all or just old derived data
  local clean_all=false
  local is_interactive=false
  if [[ -t 0 ]] && [[ -t 1 ]] && [[ -z "${MC_NON_INTERACTIVE:-}" ]]; then
    is_interactive=true
  fi
  
  if [[ "$MC_DRY_RUN" == "true" ]]; then
    # In dry-run, default to cleaning all
    clean_all=true
  elif [[ "$is_interactive" == "true" ]]; then
    print_info "Options:"
    print_info "  1) Clean all derived data (may require rebuilding all projects)"
    print_info "  2) Clean only old derived data (older than 90 days)"
    print_info "  3) Skip derived data cleanup"
    
    local choice=""
    local loop_count=0
    while [[ -z "$choice" ]]; do
      loop_count=$((loop_count + 1))
      # Use timeout to prevent hanging
      if ! read -t 30 -r "choice?Enter choice (1-3): "; then
        print_warning "Input timeout. Using default: clean only old derived data (older than 90 days)."
        clean_all=false
        break
      fi
      case "$choice" in
        1)
          clean_all=true
          ;;
        2)
          clean_all=false
          ;;
        3)
          print_info "Skipping Xcode Derived Data cleanup"
          track_space_saved "Xcode Derived Data" 0
          return 0
          ;;
        *)
          print_warning "Invalid choice. Please enter 1, 2, or 3."
          choice=""
          ;;
      esac
    done
  else
    # Non-interactive mode: default to cleaning only old items (safer default)
    print_info "Non-interactive mode: cleaning only old derived data (older than 90 days)."
    clean_all=false
  fi
  
  local total_space_freed=0
  
  if [[ "$clean_all" == "true" ]]; then
    # Clean all derived data
    local space_freed=$(_clean_xcode_dir_safe \
      "$derived_data_dir" \
      "Xcode Derived Data" \
      "xcode_derived_data")
    total_space_freed=$((total_space_freed + space_freed))
  else
    # Clean only old derived data (older than 90 days)
    print_info "Cleaning derived data older than 90 days..."
    local space_freed=$(_clean_xcode_old_items \
      "$derived_data_dir" \
      "Xcode Derived Data" \
      "xcode_derived_data" \
      90)
    total_space_freed=$((total_space_freed + space_freed))
  fi
  
  if [[ $total_space_freed -eq 0 ]]; then
    print_info "No Xcode Derived Data found to clean."
    track_space_saved "Xcode Derived Data" 0
  else
    track_space_saved "Xcode Derived Data" $total_space_freed "true"
  fi
  
  return 0
}

# Clean Xcode Device Support (with option to keep recent)
clean_xcode_device_support() {
  print_header "Cleaning Xcode Device Support"
  print_info "Device support files can be re-downloaded when devices are connected."
  
  local device_support_dir="$HOME/Library/Developer/Xcode/iOS DeviceSupport"
  if [[ ! -d "$device_support_dir" ]]; then
    print_info "No Xcode Device Support found."
    track_space_saved "Xcode Device Support" 0
    return 0
  fi
  
  # Check if user wants to clean all or just old device support
  local clean_all=false
  local is_interactive=false
  if [[ -t 0 ]] && [[ -t 1 ]] && [[ -z "${MC_NON_INTERACTIVE:-}" ]]; then
    is_interactive=true
  fi
  
  if [[ "$MC_DRY_RUN" == "true" ]]; then
    # In dry-run, default to cleaning all
    clean_all=true
  elif [[ "$is_interactive" == "true" ]]; then
    print_info "Options:"
    print_info "  1) Clean all device support (will re-download when devices connect)"
    print_info "  2) Clean only old device support (older than 90 days)"
    print_info "  3) Skip device support cleanup"
    
    local choice=""
    local loop_count=0
    while [[ -z "$choice" ]]; do
      loop_count=$((loop_count + 1))
      # Use timeout to prevent hanging
      if ! read -t 30 -r "choice?Enter choice (1-3): "; then
        print_warning "Input timeout. Using default: clean only old device support (older than 90 days)."
        clean_all=false
        break
      fi
      case "$choice" in
        1)
          clean_all=true
          ;;
        2)
          clean_all=false
          ;;
        3)
          print_info "Skipping Xcode Device Support cleanup"
          track_space_saved "Xcode Device Support" 0
          return 0
          ;;
        *)
          print_warning "Invalid choice. Please enter 1, 2, or 3."
          choice=""
          ;;
      esac
    done
  else
    # Non-interactive mode: default to cleaning only old items (safer default)
    print_info "Non-interactive mode: cleaning only old device support (older than 90 days)."
    clean_all=false
  fi
  
  local total_space_freed=0
  
  if [[ "$clean_all" == "true" ]]; then
    # Clean all device support
    local space_freed=$(_clean_xcode_dir_safe \
      "$device_support_dir" \
      "Xcode Device Support" \
      "xcode_device_support")
    total_space_freed=$((total_space_freed + space_freed))
  else
    # Clean only old device support (older than 90 days)
    print_info "Cleaning device support older than 90 days..."
    local space_freed=$(_clean_xcode_old_items \
      "$device_support_dir" \
      "Xcode Device Support" \
      "xcode_device_support" \
      90)
    total_space_freed=$((total_space_freed + space_freed))
  fi
  
  if [[ $total_space_freed -eq 0 ]]; then
    print_info "No Xcode Device Support found to clean."
    track_space_saved "Xcode Device Support" 0
  else
    track_space_saved "Xcode Device Support" $total_space_freed "true"
  fi
  
  return 0
}

# Clean Xcode Archives (with optional age filter)
clean_xcode_archives() {
  print_header "Cleaning Xcode Archives"
  print_info "Archives contain built apps. Consider backing up important archives first."
  
  local archives_dir="$HOME/Library/Developer/Xcode/Archives"
  if [[ ! -d "$archives_dir" ]]; then
    print_info "No Xcode Archives found."
    track_space_saved "Xcode Archives" 0
    return 0
  fi
  
  # Always require confirmation for archives
  if [[ "$MC_DRY_RUN" != "true" ]] && ! mc_confirm "Do you want to clean Xcode Archives?"; then
    print_info "Skipping Xcode Archives cleanup"
    track_space_saved "Xcode Archives" 0
    return 0
  fi
  
  # Check if user wants to clean all or just old archives
  local clean_all=false
  local is_interactive=false
  if [[ -t 0 ]] && [[ -t 1 ]] && [[ -z "${MC_NON_INTERACTIVE:-}" ]]; then
    is_interactive=true
  fi
  
  if [[ "$MC_DRY_RUN" == "true" ]]; then
    # In dry-run, default to cleaning all
    clean_all=true
  elif [[ "$is_interactive" == "true" ]]; then
    print_info "Options:"
    print_info "  1) Clean all archives"
    print_info "  2) Clean only old archives (older than 90 days)"
    print_info "  3) Cancel"
    
    local choice=""
    local loop_count=0
    while [[ -z "$choice" ]]; do
      loop_count=$((loop_count + 1))
      # Use timeout to prevent hanging
      if ! read -t 30 -r "choice?Enter choice (1-3): "; then
        print_warning "Input timeout. Cancelling archives cleanup."
        track_space_saved "Xcode Archives" 0
        return 0
      fi
      case "$choice" in
        1)
          clean_all=true
          ;;
        2)
          clean_all=false
          ;;
        3)
          print_info "Cancelling Xcode Archives cleanup"
          track_space_saved "Xcode Archives" 0
          return 0
          ;;
        *)
          print_warning "Invalid choice. Please enter 1, 2, or 3."
          choice=""
          ;;
      esac
    done
  else
    # Non-interactive mode: skip archives (safest default)
    print_info "Non-interactive mode: skipping archives cleanup (requires explicit confirmation)."
    track_space_saved "Xcode Archives" 0
    return 0
  fi
  
  local total_space_freed=0
  
  if [[ "$clean_all" == "true" ]]; then
    # Clean all archives
    local space_freed=$(_clean_xcode_dir_safe \
      "$archives_dir" \
      "Xcode Archives" \
      "xcode_archives")
    total_space_freed=$((total_space_freed + space_freed))
  else
    # Clean only old archives (older than 90 days)
    print_info "Cleaning archives older than 90 days..."
    local space_freed=$(_clean_xcode_old_items \
      "$archives_dir" \
      "Xcode Archives" \
      "xcode_archives" \
      90)
    total_space_freed=$((total_space_freed + space_freed))
  fi
  
  if [[ $total_space_freed -eq 0 ]]; then
    print_info "No Xcode Archives found to clean."
    track_space_saved "Xcode Archives" 0
  else
    track_space_saved "Xcode Archives" $total_space_freed "true"
  fi
  
  return 0
}

# Main cleanup function (backward compatibility)
# This function coordinates all Xcode cleanup operations
clean_xcode_data() {
  print_header "Cleaning Xcode Data"
  print_info "This will clean Xcode temporary files, caches, and build artifacts."
  print_info "Project files are never touched - only Xcode-generated data in Library/Developer."
  
  local total_space_freed=0
  local space_freed=0
  
  # 1. Clean safe temp files (no warnings, auto-clean - these are always safe)
  clean_xcode_safe_temp_files
  space_freed=$(get_space_saved "Xcode Safe Temp Files")
  total_space_freed=$((total_space_freed + space_freed))
  
  # 2. Clean derived data (with options - asks user for preferences)
  clean_xcode_derived_data
  space_freed=$(get_space_saved "Xcode Derived Data")
  total_space_freed=$((total_space_freed + space_freed))
  
  # 3. Clean device support (with options - asks user for preferences)
  clean_xcode_device_support
  space_freed=$(get_space_saved "Xcode Device Support")
  total_space_freed=$((total_space_freed + space_freed))
  
  # 4. Clean archives (requires confirmation - asks user explicitly)
  clean_xcode_archives
  space_freed=$(get_space_saved "Xcode Archives")
  total_space_freed=$((total_space_freed + space_freed))
  
  if [[ $total_space_freed -eq 0 ]]; then
    print_info "No Xcode data found to clean."
    track_space_saved "Xcode Data" 0
  else
    track_space_saved "Xcode Data" $total_space_freed "true"
    print_success "Xcode cleanup completed! Freed $(format_bytes $total_space_freed)."
  fi
  
  return 0
}

# Size calculation function for sweep
_calculate_xcode_data_size_bytes() {
  local size_bytes=0
  local xcode_size=0
  local xcode_dirs=(
    "$HOME/Library/Developer/Xcode/DerivedData"
    "$HOME/Library/Developer/Xcode/Archives"
    "$HOME/Library/Developer/Xcode/iOS DeviceSupport"
    "$HOME/Library/Caches/com.apple.dt.Xcode"
    "$HOME/Library/Developer/CoreSimulator/Caches"
    "$HOME/Library/Developer/Xcode/DocumentationCache"
  )
  for dir in "${xcode_dirs[@]}"; do
    if [[ -d "$dir" ]]; then
      local dir_size=$(calculate_size_bytes "$dir" 2>/dev/null || echo "0")
      [[ "$dir_size" =~ ^[0-9]+$ ]] && xcode_size=$((xcode_size + dir_size))
    fi
  done
  size_bytes=$xcode_size
  echo "$size_bytes"
}

# Register plugin with size function
register_plugin "Xcode Data" "development" "clean_xcode_data" "false" "_calculate_xcode_data_size_bytes"
