#!/bin/bash
# Home Network Monitor - Docker Management
# Docker Compose management (compose, containers)
# Compatible with macOS default Bash 3.2

# Prevent direct execution
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  echo "This is a library file and should be sourced, not executed."
  exit 1
fi

#------------------------------------------------------------------------------
# Docker Management
#------------------------------------------------------------------------------

generate_compose_file() {
  : "${COMPOSE_FILE:=${BASE_DIR}/docker-compose.yml}"
  : "${BASE_DIR:=${HOME}/home-netmon}"
  
  if command -v log_info >/dev/null 2>&1; then
    log_info "Generating docker-compose.yml"
  fi
  cat > "$COMPOSE_FILE" <<'YAML'
# Home Network Monitor - Docker Compose Configuration
# Generated by setup-home-netmon.sh
# Do not edit manually - changes will be overwritten on update

services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: home-netmon-gatus
    restart: unless-stopped
    ports:
      - "${GATUS_PORT}:8080"
    volumes:
      - "./gatus:/config"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: home-netmon-ntfy
    restart: unless-stopped
    ports:
      - "${NTFY_PORT}:80"
    volumes:
      - "./ntfy:/var/lib/ntfy"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
YAML
  if command -v log_info >/dev/null 2>&1; then
    log_info "docker-compose.yml generated"
  fi
}

start_containers() {
  : "${BASE_DIR:=${HOME}/home-netmon}"
  : "${ENV_FILE:=${BASE_DIR}/.env}"
  : "${COMPOSE_FILE:=${BASE_DIR}/docker-compose.yml}"
  
  if containers_running; then
    if command -v say >/dev/null 2>&1; then
      say "Containers are already running. Updating configuration..."
    fi
    if command -v log_info >/dev/null 2>&1; then
      log_info "Containers already running, performing update"
    fi
    cd "$BASE_DIR"
    docker compose --env-file "$ENV_FILE" up -d
  else
    if command -v say >/dev/null 2>&1; then
      say "Starting Docker containers..."
    fi
    if command -v log_info >/dev/null 2>&1; then
      log_info "Starting Docker containers"
    fi
    cd "$BASE_DIR"
    docker compose --env-file "$ENV_FILE" up -d
    
    # Wait a moment for containers to start
    sleep 3
  fi
  
  if command -v log_info >/dev/null 2>&1; then
    log_info "Docker containers started"
  fi
}

stop_containers() {
  : "${BASE_DIR:=${HOME}/home-netmon}"
  : "${COMPOSE_FILE:=${BASE_DIR}/docker-compose.yml}"
  
  if [ ! -f "$COMPOSE_FILE" ]; then
    return 1
  fi
  
  cd "$BASE_DIR"
  docker compose down
}

restart_containers() {
  stop_containers
  sleep 2
  start_containers
}

get_container_status() {
  : "${BASE_DIR:=${HOME}/home-netmon}"
  : "${COMPOSE_FILE:=${BASE_DIR}/docker-compose.yml}"
  
  if [ ! -f "$COMPOSE_FILE" ]; then
    return 1
  fi
  
  cd "$BASE_DIR"
  docker compose ps
}

verify_containers() {
  : "${BASE_DIR:=${HOME}/home-netmon}"
  : "${ENV_FILE:=${BASE_DIR}/.env}"
  
  local errors=0
  
  if ! containers_running; then
    if command -v err >/dev/null 2>&1; then
      err "Containers are not running"
    fi
    if command -v log_error >/dev/null 2>&1; then
      log_error "Container verification failed"
    fi
    errors=$((errors + 1))
  else
    if command -v info >/dev/null 2>&1; then
      info "✓ Containers are running"
    fi
    if command -v log_info >/dev/null 2>&1; then
      log_info "Container verification passed"
    fi
  fi
  
  # Check Gatus port
  local gatus_port
  gatus_port=$(get_env_value "GATUS_PORT")
  if [ -n "$gatus_port" ]; then
    if command_exists curl; then
      if curl -sf "http://localhost:${gatus_port}" >/dev/null 2>&1; then
        if command -v info >/dev/null 2>&1; then
          info "✓ Gatus is accessible on port ${gatus_port}"
        fi
        if command -v log_info >/dev/null 2>&1; then
          log_info "Gatus accessibility check passed"
        fi
      else
        if command -v warn >/dev/null 2>&1; then
          warn "Gatus may not be fully ready on port ${gatus_port} (this is normal if it just started)"
        fi
        if command -v log_warn >/dev/null 2>&1; then
          log_warn "Gatus accessibility check: service may still be starting"
        fi
      fi
    fi
  fi
  
  # Check ntfy port
  local ntfy_port
  ntfy_port=$(get_env_value "NTFY_PORT")
  if [ -n "$ntfy_port" ]; then
    if command_exists curl; then
      if curl -sf "http://localhost:${ntfy_port}" >/dev/null 2>&1; then
        if command -v info >/dev/null 2>&1; then
          info "✓ ntfy is accessible on port ${ntfy_port}"
        fi
        if command -v log_info >/dev/null 2>&1; then
          log_info "ntfy accessibility check passed"
        fi
      else
        if command -v warn >/dev/null 2>&1; then
          warn "ntfy may not be fully ready on port ${ntfy_port} (this is normal if it just started)"
        fi
        if command -v log_warn >/dev/null 2>&1; then
          log_warn "ntfy accessibility check: service may still be starting"
        fi
      fi
    fi
  fi
  
  return $errors
}
