#!/bin/bash
# Home Network Monitor - Gatus Configuration
# Gatus configuration generation
# Compatible with macOS default Bash 3.2

# Prevent direct execution
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  echo "This is a library file and should be sourced, not executed."
  exit 1
fi

#------------------------------------------------------------------------------
# Gatus Configuration Functions
#------------------------------------------------------------------------------

generate_gatus_config() {
  : "${GATUS_DIR:=${BASE_DIR}/gatus}"
  : "${BASE_DIR:=${HOME}/home-netmon}"
  local config_file="${GATUS_DIR}/config.yaml"
  local router_ip
  
  mkdir -p "$GATUS_DIR"
  
  # Get router IP from .env if available
  router_ip=$(get_env_value "ROUTER_IP")
  
  # Generate initial Gatus configuration
  cat > "$config_file" <<YAML
# Gatus Configuration
# Generated by setup-home-netmon.sh
# You can customize this file manually

services:
  - name: Router Ping
    url: "icmp://${router_ip:-192.168.1.1}"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == success"
YAML

  if command -v log_info >/dev/null 2>&1; then
    log_info "Generated initial Gatus configuration"
  fi
}

add_gatus_endpoint() {
  local name="$1"
  local url="$2"
  local interval="${3:-60s}"
  : "${GATUS_DIR:=${BASE_DIR}/gatus}"
  local config_file="${GATUS_DIR}/config.yaml"
  
  if [ ! -f "$config_file" ]; then
    generate_gatus_config
  fi
  
  # Add endpoint to config (simple append for now)
  cat >> "$config_file" <<YAML

  - name: "$name"
    url: "$url"
    interval: "$interval"
    conditions:
      - "[STATUS] == 200"
YAML

  if command -v log_info >/dev/null 2>&1; then
    log_info "Added Gatus endpoint: $name"
  fi
}

update_gatus_config() {
  : "${GATUS_DIR:=${BASE_DIR}/gatus}"
  local config_file="${GATUS_DIR}/config.yaml"
  
  if [ ! -f "$config_file" ]; then
    generate_gatus_config
    return 0
  fi
  
  # For now, just regenerate if needed
  # In the future, this could merge updates intelligently
  if command -v log_info >/dev/null 2>&1; then
    log_info "Gatus configuration exists, skipping regeneration"
  fi
}
