#!/usr/bin/env bash

#==============================================================================
# backup.sh - Configuration Backup
#
# Handles backup and restore of configuration files
#==============================================================================

# Load dependencies
if [[ -n "${ZSH_SETUP_ROOT:-}" ]]; then
    source "$ZSH_SETUP_ROOT/lib/core/config.sh"
    source "$ZSH_SETUP_ROOT/lib/core/logger.sh"
    source "$ZSH_SETUP_ROOT/lib/utils/filesystem.sh"
    # Load progress module if available
    if [[ -f "$ZSH_SETUP_ROOT/lib/core/progress.sh" ]]; then
        source "$ZSH_SETUP_ROOT/lib/core/progress.sh" 2>/dev/null || true
    fi
fi

#------------------------------------------------------------------------------
# Backup Functions
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Function: zsh_setup::config::backup::extract_custom_configs
# Description: Intelligently extracts custom configurations from existing .zshrc
#              Identifies and preserves ALL custom content including:
#              - Custom environment variables
#              - Custom aliases and functions
#              - Lazy loading configurations
#              - Tool-specific setups (pyenv, nvm, rvm, etc.)
# Arguments:
#   None
# Returns:
#   0 on success, 1 if .zshrc doesn't exist
# Side Effects:
#   Creates or overwrites ~/.zshrc.local with extracted custom configs
#   Backs up existing .zshrc.local if present
#------------------------------------------------------------------------------
zsh_setup::config::backup::extract_custom_configs() {
    local zshrc_path="$HOME/.zshrc"
    local local_config="$HOME/.zshrc.local"

    # Check if .zshrc exists
    if [[ ! -f "$zshrc_path" ]]; then
        zsh_setup::core::logger::info "No existing .zshrc found. Nothing to extract."
        return 0
    fi

    zsh_setup::core::logger::info "Analyzing existing .zshrc for custom configurations..."

    # Backup existing .zshrc.local if present
    if [[ -f "$local_config" ]]; then
        local timestamp=$(date "+%Y%m%d_%H%M%S")
        local backup_path="${local_config}.backup.$timestamp"
        cp "$local_config" "$backup_path"
        zsh_setup::core::logger::info "Backed up existing .zshrc.local to $backup_path"
    fi

    # Create temporary file for extracted configs
    local temp_file=$(mktemp)

    # Write header
    cat > "$temp_file" <<'EOF'
#==============================================================================
# Custom Configurations (extracted from previous .zshrc)
#==============================================================================
# This file was automatically generated by zsh-setup on $(date "+%Y-%m-%d %H:%M:%S")
# All custom configurations from your previous .zshrc have been preserved here.
#==============================================================================

EOF

    # State machine variables
    local in_custom_env=false
    local in_custom_section=false
    local in_omz_section=false
    local custom_env_vars=""
    local custom_aliases=""
    local custom_functions=""
    local custom_other=""
    local current_section=""
    local current_function=""
    local brace_count=0
    local line_buffer=""

    # Read and categorize content
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip completely empty lines during parsing
        if [[ -z "$line" ]] && [[ -z "$current_function" ]]; then
            continue
        fi

        # Detect Oh My Zsh standard boilerplate (SKIP these)
        if [[ "$line" =~ ^[[:space:]]*export[[:space:]]+ZSH= ]] || \
           [[ "$line" =~ ^[[:space:]]*ZSH_THEME= ]] || \
           [[ "$line" =~ ^[[:space:]]*plugins=\( ]] || \
           [[ "$line" =~ ^[[:space:]]*source[[:space:]]+.*/oh-my-zsh\.sh ]] || \
           [[ "$line" =~ ^[[:space:]]*HYPHEN_INSENSITIVE= ]] || \
           [[ "$line" =~ ^[[:space:]]*DISABLE_UPDATE_PROMPT= ]] || \
           [[ "$line" =~ ^[[:space:]]*COMPLETION_WAITING_DOTS= ]] || \
           [[ "$line" =~ "source.*p10k\.zsh" ]] || \
           [[ "$line" =~ "To customize prompt.*p10k configure" ]] || \
           [[ "$line" =~ "Generated by zsh-setup" ]]; then
            in_omz_section=true
            continue
        fi

        # Detect plugin-specific sources (handled by our installer)
        if [[ "$line" =~ "source.*zsh-syntax-highlighting\.zsh" ]] || \
           [[ "$line" =~ "source.*autojump\.zsh" ]] || \
           [[ "$line" =~ "source.*fzf\.zsh" ]]; then
            continue
        fi

        # Detect section headers and categorize content
        if [[ "$line" =~ ^[[:space:]]*#.*$ ]]; then
            # This is a comment - check if it's a section header
            if [[ "$line" =~ ^#=+ ]] || [[ "$line" =~ ^#-+ ]]; then
                # Major section header - preserve it
                if [[ "$line" =~ (Environment|Export|Variable) ]]; then
                    in_custom_env=true
                    custom_env_vars+="$line"$'\n'
                elif [[ "$line" =~ (Alias|Command|Shortcut) ]]; then
                    in_custom_env=false
                    custom_aliases+="$line"$'\n'
                elif [[ "$line" =~ (Function|Tool|Setup|Load|Lazy) ]]; then
                    in_custom_env=false
                    custom_functions+="$line"$'\n'
                else
                    custom_other+="$line"$'\n'
                fi
            else
                # Regular comment - add to current section
                if [[ -n "$current_function" ]]; then
                    current_function+="$line"$'\n'
                elif [[ "$in_custom_env" == "true" ]]; then
                    custom_env_vars+="$line"$'\n'
                else
                    custom_other+="$line"$'\n'
                fi
            fi
            continue
        fi

        # Track function definitions (preserve multi-line functions)
        if [[ "$line" =~ ^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*\(\)[[:space:]]*\{ ]]; then
            # Function definition start
            current_function="$line"$'\n'
            brace_count=1
            continue
        elif [[ -n "$current_function" ]]; then
            # Inside function definition
            current_function+="$line"$'\n'

            # Count braces to detect end of function
            local open_braces=$(echo "$line" | tr -cd '{' | wc -c)
            local close_braces=$(echo "$line" | tr -cd '}' | wc -c)
            brace_count=$((brace_count + open_braces - close_braces))

            if [[ $brace_count -le 0 ]]; then
                # Function complete - add to functions section
                custom_functions+="$current_function"$'\n'
                current_function=""
                brace_count=0
            fi
            continue
        fi

        # Categorize non-comment, non-function lines
        if [[ "$line" =~ ^[[:space:]]*export[[:space:]] ]] || \
           [[ "$line" =~ ^[[:space:]]*[A-Z_][A-Z0-9_]*= ]]; then
            # Environment variable or export
            custom_env_vars+="$line"$'\n'
        elif [[ "$line" =~ ^[[:space:]]*alias[[:space:]] ]]; then
            # Alias definition
            custom_aliases+="$line"$'\n'
        elif [[ "$line" =~ "autoload -U" ]] || \
             [[ "$line" =~ "add-zsh-hook" ]] || \
             [[ "$line" =~ "eval.*init" ]] || \
             [[ "$line" =~ "fpath=" ]] || \
             [[ "$line" =~ "compinit" ]]; then
            # Tool setup / lazy loading
            custom_functions+="$line"$'\n'
        else
            # Other custom configuration
            custom_other+="$line"$'\n'
        fi
    done < "$zshrc_path"

    # Assemble final configuration file
    local has_content=false

    if [[ -n "$custom_env_vars" ]]; then
        cat >> "$temp_file" <<EOF

#------------------------------------------------------------------------------
# Environment Variables
#------------------------------------------------------------------------------
$custom_env_vars
EOF
        has_content=true
    fi

    if [[ -n "$custom_functions" ]]; then
        cat >> "$temp_file" <<EOF

#------------------------------------------------------------------------------
# Functions and Tool Setup
#------------------------------------------------------------------------------
$custom_functions
EOF
        has_content=true
    fi

    if [[ -n "$custom_aliases" ]]; then
        cat >> "$temp_file" <<EOF

#------------------------------------------------------------------------------
# Aliases
#------------------------------------------------------------------------------
$custom_aliases
EOF
        has_content=true
    fi

    if [[ -n "$custom_other" ]]; then
        cat >> "$temp_file" <<EOF

#------------------------------------------------------------------------------
# Other Custom Configurations
#------------------------------------------------------------------------------
$custom_other
EOF
        has_content=true
    fi

    # Save to .zshrc.local if we found anything
    if [[ "$has_content" == "true" ]]; then
        mv "$temp_file" "$local_config"
        chmod 644 "$local_config"
        zsh_setup::core::logger::success "Extracted custom configurations to ~/.zshrc.local"

        # Show summary
        local env_count=$(echo "$custom_env_vars" | grep -c "export\|^[A-Z_]" || echo "0")
        local alias_count=$(echo "$custom_aliases" | grep -c "^alias" || echo "0")
        local func_count=$(echo "$custom_functions" | grep -c "()" || echo "0")

        zsh_setup::core::logger::info "  ├─ Environment variables: $env_count"
        zsh_setup::core::logger::info "  ├─ Aliases: $alias_count"
        zsh_setup::core::logger::info "  └─ Functions/Tools: $func_count"
    else
        rm -f "$temp_file"
        zsh_setup::core::logger::info "No custom configurations found to extract"
    fi

    return 0
}

# Backup Zsh configuration files
zsh_setup::config::backup::backup_zshrc() {
    local backup_dir=$(zsh_setup::core::config::get backup_dir "$HOME/.zsh_backup")
    local timestamp=$(date "+%Y%m%d_%H%M%S")
    local files_backed_up=0
    
    local spinner_pid=""
    if declare -f zsh_setup::core::progress::spinner_start &>/dev/null; then
        spinner_pid=$(zsh_setup::core::progress::spinner_start "Backing up existing Zsh configuration")
    else
        zsh_setup::core::logger::info "Backing up existing Zsh configuration..."
    fi
    
    # Ensure backup directory exists
    zsh_setup::utils::filesystem::ensure_dir "$backup_dir"
    
    # Files to backup
    local config_files=(
        ".zshrc"
        ".zshenv"
        ".zprofile"
        ".zlogin"
        ".zlogout"
    )
    
    # Backup each file
    for file in "${config_files[@]}"; do
        local path="$HOME/$file"
        if [[ -f "$path" ]]; then
            cp "$path" "$backup_dir/$file.$timestamp" 2>/dev/null && {
                ((files_backed_up++))
            }
        fi
    done
    
    # Check for existing Oh My Zsh
    local ohmyzsh_dir=$(zsh_setup::core::config::get oh_my_zsh_dir)
    if [[ -d "$ohmyzsh_dir" ]]; then
        if [[ -n "$spinner_pid" ]]; then
            zsh_setup::core::progress::spinner_stop "$spinner_pid" "" "" 0
        fi
        zsh_setup::core::logger::warn "Existing Oh My Zsh installation found. Will not overwrite."
    fi
    
    if [[ -n "$spinner_pid" ]]; then
        if [[ $files_backed_up -eq 0 ]]; then
            zsh_setup::core::progress::spinner_stop "$spinner_pid" "No existing Zsh configuration files found. No backups created." "" 0
        else
            zsh_setup::core::progress::spinner_stop "$spinner_pid" "✅ Backup completed. $files_backed_up files backed up to $backup_dir" "" 0
        fi
    else
        if [[ $files_backed_up -eq 0 ]]; then
            zsh_setup::core::logger::info "No existing Zsh configuration files found. No backups created."
        else
            zsh_setup::core::logger::success "Backup completed. $files_backed_up files backed up to $backup_dir"
        fi
    fi
}

# Restore from backup
zsh_setup::config::backup::restore() {
    local backup_file="$1"
    local target_file="${2:-$HOME/.zshrc}"
    
    if [[ ! -f "$backup_file" ]]; then
        zsh_setup::core::logger::error "Backup file not found: $backup_file"
        return 1
    fi
    
    zsh_setup::core::logger::info "Restoring from backup: $backup_file"
    
    if cp "$backup_file" "$target_file"; then
        zsh_setup::core::logger::success "Restored $target_file from backup"
        return 0
    else
        zsh_setup::core::logger::error "Failed to restore from backup"
        return 1
    fi
}

# List available backups
zsh_setup::config::backup::list() {
    local backup_dir=$(zsh_setup::core::config::get backup_dir "$HOME/.zsh_backup")
    
    if [[ ! -d "$backup_dir" ]]; then
        zsh_setup::core::logger::info "No backup directory found"
        return 0
    fi
    
    echo "Available backups in $backup_dir:"
    ls -lt "$backup_dir" 2>/dev/null | head -10
}

