#!/usr/bin/env bash

#==============================================================================
# backup.sh - Configuration Backup
#
# Handles backup and restore of configuration files
#==============================================================================

# Load dependencies
if [[ -n "${ZSH_SETUP_ROOT:-}" ]]; then
    source "$ZSH_SETUP_ROOT/lib/core/config.sh"
    source "$ZSH_SETUP_ROOT/lib/core/logger.sh"
    source "$ZSH_SETUP_ROOT/lib/utils/filesystem.sh"
    # Load progress module if available
    if [[ -f "$ZSH_SETUP_ROOT/lib/core/progress.sh" ]]; then
        source "$ZSH_SETUP_ROOT/lib/core/progress.sh" 2>/dev/null || true
    fi
fi

#------------------------------------------------------------------------------
# Backup Functions
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Function: zsh_setup::config::backup::extract_custom_configs
# Description: Extracts custom configurations from existing .zshrc to .zshrc.local
# Arguments:
#   None
# Returns:
#   0 on success, 1 if .zshrc doesn't exist
# Side Effects:
#   Creates or appends to ~/.zshrc.local
#   Backs up existing .zshrc.local if present
#------------------------------------------------------------------------------
zsh_setup::config::backup::extract_custom_configs() {
    local zshrc_path="$HOME/.zshrc"
    local local_config="$HOME/.zshrc.local"

    # Check if .zshrc exists
    if [[ ! -f "$zshrc_path" ]]; then
        zsh_setup::core::logger::info "No existing .zshrc found. Nothing to extract."
        return 0
    fi

    # Check if it's a zsh-setup generated file
    if ! grep -q "Generated by zsh-setup" "$zshrc_path" 2>/dev/null; then
        # This is a custom .zshrc - user needs to decide what to do
        zsh_setup::core::logger::warn "Existing .zshrc is not generated by zsh-setup."
        zsh_setup::core::logger::info "Your current .zshrc will be backed up, but custom configs won't be auto-extracted."
        zsh_setup::core::logger::info "After installation, you can manually move custom configs to ~/.zshrc.local"
        return 0
    fi

    # Extract custom section (anything after custom configurations marker)
    # Look for various markers: "User Custom", "Local User Customizations", etc.
    local custom_section=""
    local in_custom_section=false
    local found_marker=false

    while IFS= read -r line; do
        # Check for custom section markers (flexible matching)
        if [[ "$line" =~ (User.*Custom|Local.*Custom|Custom.*Config) ]] && [[ "$line" =~ ^[[:space:]]*# ]]; then
            in_custom_section=true
            found_marker=true
            continue
        fi

        # Collect content after marker
        if [[ "$in_custom_section" == "true" ]]; then
            # Skip comment lines, blank lines, and the source statement itself
            if [[ "$line" =~ ^[[:space:]]*#.*$ ]] || \
               [[ "$line" =~ "source.*zshrc.local" ]] || \
               [[ "$line" =~ ^\[.*zshrc.local.*\] ]] || \
               [[ -z "$line" ]]; then
                continue
            fi
            # Add non-empty content
            custom_section+="$line"$'\n'
        fi
    done < "$zshrc_path"

    # If we found custom configs, save them to .zshrc.local
    if [[ -n "$custom_section" ]]; then
        # Backup existing .zshrc.local if present
        if [[ -f "$local_config" ]]; then
            local timestamp=$(date "+%Y%m%d_%H%M%S")
            local backup_path="${local_config}.backup.$timestamp"
            cp "$local_config" "$backup_path"
            zsh_setup::core::logger::info "Backed up existing .zshrc.local to $backup_path"
        fi

        # Write extracted configs
        cat >> "$local_config" <<EOF
#------------------------------------------------------------------------------
# Extracted from previous .zshrc ($(date "+%Y-%m-%d %H:%M:%S"))
#------------------------------------------------------------------------------

$custom_section
EOF
        zsh_setup::core::logger::success "Extracted custom configurations to ~/.zshrc.local"
    else
        zsh_setup::core::logger::info "No custom configurations found in existing .zshrc"
    fi

    return 0
}

# Backup Zsh configuration files
zsh_setup::config::backup::backup_zshrc() {
    local backup_dir=$(zsh_setup::core::config::get backup_dir "$HOME/.zsh_backup")
    local timestamp=$(date "+%Y%m%d_%H%M%S")
    local files_backed_up=0
    
    local spinner_pid=""
    if declare -f zsh_setup::core::progress::spinner_start &>/dev/null; then
        spinner_pid=$(zsh_setup::core::progress::spinner_start "Backing up existing Zsh configuration")
    else
        zsh_setup::core::logger::info "Backing up existing Zsh configuration..."
    fi
    
    # Ensure backup directory exists
    zsh_setup::utils::filesystem::ensure_dir "$backup_dir"
    
    # Files to backup
    local config_files=(
        ".zshrc"
        ".zshenv"
        ".zprofile"
        ".zlogin"
        ".zlogout"
    )
    
    # Backup each file
    for file in "${config_files[@]}"; do
        local path="$HOME/$file"
        if [[ -f "$path" ]]; then
            cp "$path" "$backup_dir/$file.$timestamp" 2>/dev/null && {
                ((files_backed_up++))
            }
        fi
    done
    
    # Check for existing Oh My Zsh
    local ohmyzsh_dir=$(zsh_setup::core::config::get oh_my_zsh_dir)
    if [[ -d "$ohmyzsh_dir" ]]; then
        if [[ -n "$spinner_pid" ]]; then
            zsh_setup::core::progress::spinner_stop "$spinner_pid" "" "" 0
        fi
        zsh_setup::core::logger::warn "Existing Oh My Zsh installation found. Will not overwrite."
    fi
    
    if [[ -n "$spinner_pid" ]]; then
        if [[ $files_backed_up -eq 0 ]]; then
            zsh_setup::core::progress::spinner_stop "$spinner_pid" "No existing Zsh configuration files found. No backups created." "" 0
        else
            zsh_setup::core::progress::spinner_stop "$spinner_pid" "✅ Backup completed. $files_backed_up files backed up to $backup_dir" "" 0
        fi
    else
        if [[ $files_backed_up -eq 0 ]]; then
            zsh_setup::core::logger::info "No existing Zsh configuration files found. No backups created."
        else
            zsh_setup::core::logger::success "Backup completed. $files_backed_up files backed up to $backup_dir"
        fi
    fi
}

# Restore from backup
zsh_setup::config::backup::restore() {
    local backup_file="$1"
    local target_file="${2:-$HOME/.zshrc}"
    
    if [[ ! -f "$backup_file" ]]; then
        zsh_setup::core::logger::error "Backup file not found: $backup_file"
        return 1
    fi
    
    zsh_setup::core::logger::info "Restoring from backup: $backup_file"
    
    if cp "$backup_file" "$target_file"; then
        zsh_setup::core::logger::success "Restored $target_file from backup"
        return 0
    else
        zsh_setup::core::logger::error "Failed to restore from backup"
        return 1
    fi
}

# List available backups
zsh_setup::config::backup::list() {
    local backup_dir=$(zsh_setup::core::config::get backup_dir "$HOME/.zsh_backup")
    
    if [[ ! -d "$backup_dir" ]]; then
        zsh_setup::core::logger::info "No backup directory found"
        return 0
    fi
    
    echo "Available backups in $backup_dir:"
    ls -lt "$backup_dir" 2>/dev/null | head -10
}

