#!/usr/bin/env bash

#==============================================================================
# generator.sh - Configuration Generator
#
# Generates .zshrc configuration file
#==============================================================================

# Load dependencies
if [[ -n "${ZSH_SETUP_ROOT:-}" ]]; then
    source "$ZSH_SETUP_ROOT/lib/core/config.sh"
    source "$ZSH_SETUP_ROOT/lib/core/logger.sh"
    source "$ZSH_SETUP_ROOT/lib/state/store.sh"
fi

#------------------------------------------------------------------------------
# Configuration Generation
#------------------------------------------------------------------------------

# Generate .zshrc file
zsh_setup::config::generator::generate() {
    local zshrc_path=$(zsh_setup::core::config::get zshrc_path "$HOME/.zshrc")
    local temp_zshrc=$(mktemp)
    
    zsh_setup::core::logger::info "Generating Zsh configuration..."
    
    # Build configuration
    zsh_setup::config::generator::_generate_header "$temp_zshrc"
    zsh_setup::config::generator::_generate_theme "$temp_zshrc"
    zsh_setup::config::generator::_generate_ohmyzsh_settings "$temp_zshrc"
    zsh_setup::config::generator::_generate_plugins "$temp_zshrc"
    zsh_setup::config::generator::_generate_environment "$temp_zshrc"
    zsh_setup::config::generator::_generate_footer "$temp_zshrc"
    
    # Move to final location
    mv "$temp_zshrc" "$zshrc_path"
    zsh_setup::core::logger::success "Zsh configuration generated at $zshrc_path"
}

# Generate header
zsh_setup::config::generator::_generate_header() {
    local file="$1"
    cat >"$file" <<'EOF'
#==============================================================================
# Zsh Configuration
# Generated by zsh-setup
#==============================================================================

# Path to Oh My Zsh installation
export ZSH="$HOME/.oh-my-zsh"

EOF
}

# Generate theme configuration
zsh_setup::config::generator::_generate_theme() {
    local file="$1"
    local theme=$(zsh_setup::core::config::get default_theme "robbyrussell")
    
    # Check if powerlevel10k is installed
    local installed_plugins=()
    while IFS= read -r plugin; do
        [[ -n "$plugin" ]] && installed_plugins+=("$plugin")
    done < <(zsh_setup::state::store::get_installed_plugins 2>/dev/null)
    
    if printf '%s\n' "${installed_plugins[@]}" | grep -q "^powerlevel10k$"; then
        theme="powerlevel10k/powerlevel10k"
    fi
    
    cat >>"$file" <<EOF
# Set theme
ZSH_THEME="$theme"

EOF
}

# Generate Oh My Zsh settings
zsh_setup::config::generator::_generate_ohmyzsh_settings() {
    local file="$1"
    cat >>"$file" <<'EOF'
# Oh My Zsh settings
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

EOF
}

# Generate plugins section
zsh_setup::config::generator::_generate_plugins() {
    local file="$1"
    local plugins=("git")
    
    # Get installed plugins
    local installed_plugins=()
    while IFS= read -r plugin; do
        [[ -n "$plugin" ]] && installed_plugins+=("$plugin")
    done < <(zsh_setup::state::store::get_installed_plugins 2>/dev/null)
    
    # Add plugins (skip powerlevel10k as it's a theme)
    for plugin in "${installed_plugins[@]}"; do
        [[ "$plugin" == "powerlevel10k" ]] && continue
        local ohmyzsh_dir=$(zsh_setup::core::config::get oh_my_zsh_dir)
        if [[ -d "$ohmyzsh_dir/plugins/$plugin" ]] || [[ -d "$ohmyzsh_dir/custom/plugins/$plugin" ]]; then
            plugins+=("$plugin")
        fi
    done
    
    cat >>"$file" <<EOF
# Plugins
plugins=(${plugins[*]})

EOF
    
    # Add plugin-specific configs
    zsh_setup::config::generator::_generate_plugin_configs "$file" "${installed_plugins[@]}"
}

# Generate plugin-specific configurations
zsh_setup::config::generator::_generate_plugin_configs() {
    local file="$1"
    shift
    local plugins=("$@")
    
    cat >>"$file" <<'EOF'
#------------------------------------------------------------------------------
# Plugin Configurations
#------------------------------------------------------------------------------

EOF
    
    # Add specific plugin configs
    for plugin in "${plugins[@]}"; do
        case "$plugin" in
            nvm)
                cat >>"$file" <<'EOF'
# NVM configuration
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

EOF
                ;;
            zsh-syntax-highlighting)
                # Will be added at the end
                ;;
        esac
    done
    
    # Add syntax highlighting at the end if installed
    if printf '%s\n' "${plugins[@]}" | grep -q "^zsh-syntax-highlighting$"; then
        cat >>"$file" <<'EOF'
# Syntax highlighting (must be loaded last)
source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

EOF
    fi
}

# Generate environment variables
zsh_setup::config::generator::_generate_environment() {
    local file="$1"
    
    cat >>"$file" <<'EOF'
#------------------------------------------------------------------------------
# Environment Variables
#------------------------------------------------------------------------------

# PATH configuration
EOF
    
    # Build PATH
    zsh_setup::config::generator::_build_path "$file"
    
    # Add other environment variables
    cat >>"$file" <<'EOF'

# Editor
export EDITOR="${EDITOR:-vim}"

# Java (macOS)
if [[ "$OSTYPE" == "darwin"* ]] && [[ -z "$JAVA_HOME" ]]; then
    if [ -f "/usr/libexec/java_home" ]; then
        export JAVA_HOME=$(/usr/libexec/java_home)
        export PATH="$JAVA_HOME/bin:$PATH"
    fi
fi

# Python (user install)
if command -v python3 &>/dev/null; then
    local python_path=$(python3 -m site --user-base 2>/dev/null)
    if [[ -n "$python_path" ]]; then
        export PATH="$python_path/bin:$PATH"
    fi
fi

EOF
}

# Build PATH
zsh_setup::config::generator::_build_path() {
    local file="$1"
    
    # System paths
    local system_paths=(
        "/usr/local/bin"
        "/usr/local/sbin"
        "/usr/bin"
        "/bin"
        "/usr/sbin"
        "/sbin"
    )
    
    # Homebrew paths (macOS)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        if [[ -d "/opt/homebrew" ]]; then
            system_paths+=("/opt/homebrew/bin" "/opt/homebrew/sbin")
        elif [[ -d "/usr/local/Homebrew" ]]; then
            system_paths+=("/usr/local/bin" "/usr/local/sbin")
        fi
    fi
    
    # Build PATH export
    echo "export PATH=\"" >>"$file"
    for path in "${system_paths[@]}"; do
        [[ -d "$path" ]] && echo "  $path:" >>"$file"
    done
    echo '  $PATH"' >>"$file"
}

# Generate footer
zsh_setup::config::generator::_generate_footer() {
    local file="$1"
    cat >>"$file" <<'EOF'

#------------------------------------------------------------------------------
# Initialize Oh My Zsh
#------------------------------------------------------------------------------

source $ZSH/oh-my-zsh.sh

EOF
}

# Backward compatibility
generate_zsh_config() {
    zsh_setup::config::generator::generate
}

generate_zshrc() {
    zsh_setup::config::generator::generate
}
