#!/usr/bin/env bash

#==============================================================================
# migrate-custom-configs.sh - Migrate Custom Configurations
#
# Extracts custom configurations from current .zshrc to .zshrc.local
# Run this BEFORE running zsh-setup install to preserve your customizations
#==============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Migrate Custom .zshrc Configurations                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZSHRC_PATH="$HOME/.zshrc"
LOCAL_CONFIG="$HOME/.zshrc.local"

# Check if .zshrc exists
if [[ ! -f "$ZSHRC_PATH" ]]; then
    echo -e "${YELLOW}⚠️  No .zshrc file found at $ZSHRC_PATH${NC}"
    echo "Nothing to migrate."
    exit 0
fi

echo -e "${BLUE}Current .zshrc:${NC} $ZSHRC_PATH"
echo

# Show preview of what will be migrated
echo -e "${BLUE}Detecting custom configurations...${NC}"
echo

# Check if it's a zsh-setup generated file
if grep -q "Generated by zsh-setup" "$ZSHRC_PATH" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Detected zsh-setup generated .zshrc"

    # Extract custom section
    custom_section=$(awk '/User Custom Configurations/,0' "$ZSHRC_PATH" | \
        grep -v "^[[:space:]]*#" | \
        grep -v "source.*zshrc.local" | \
        grep -v "^[[:space:]]*$" || true)

    if [[ -z "$custom_section" ]]; then
        echo -e "${GREEN}✓${NC} No custom configurations found"
        echo "Your .zshrc only contains generated content. Nothing to migrate."
        exit 0
    fi

    echo -e "${YELLOW}Found custom configurations:${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "$custom_section"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
else
    echo -e "${YELLOW}⚠️  Your .zshrc is not generated by zsh-setup${NC}"
    echo
    echo "This script can only auto-extract from zsh-setup generated files."
    echo "You have two options:"
    echo
    echo "  1. Manually create ~/.zshrc.local with your custom configs"
    echo "  2. Let zsh-setup backup your current .zshrc and start fresh"
    echo
    echo "Your current .zshrc will be backed up to ~/.zsh_backup/ during installation."
    exit 0
fi

# Ask for confirmation
echo -e "${YELLOW}What would you like to do?${NC}"
echo "  1. Migrate to .zshrc.local (recommended)"
echo "  2. View full .zshrc first"
echo "  3. Cancel"
echo
read -p "Enter choice [1-3]: " choice

case "$choice" in
    1)
        # Backup existing .zshrc.local if present
        if [[ -f "$LOCAL_CONFIG" ]]; then
            timestamp=$(date "+%Y%m%d_%H%M%S")
            backup_path="${LOCAL_CONFIG}.backup.$timestamp"
            cp "$LOCAL_CONFIG" "$backup_path"
            echo -e "${GREEN}✓${NC} Backed up existing .zshrc.local to $backup_path"
        fi

        # Write extracted configs
        cat >> "$LOCAL_CONFIG" <<EOF
#------------------------------------------------------------------------------
# Migrated from .zshrc ($(date "+%Y-%m-%d %H:%M:%S"))
#------------------------------------------------------------------------------

$custom_section
EOF

        echo -e "${GREEN}✓${NC} Migrated custom configurations to $LOCAL_CONFIG"
        echo
        echo -e "${GREEN}Success!${NC} Your custom configurations have been preserved."
        echo
        echo "Next steps:"
        echo "  1. Review $LOCAL_CONFIG to verify everything migrated correctly"
        echo "  2. Run: ./zsh-setup install"
        echo "  3. Your new .zshrc will automatically source .zshrc.local"
        echo
        ;;

    2)
        echo
        echo "Current .zshrc contents:"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        cat "$ZSHRC_PATH"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        echo "Re-run this script when ready to migrate."
        ;;

    3|*)
        echo -e "${YELLOW}Migration cancelled.${NC}"
        exit 0
        ;;
esac
